import { readFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { describe, expect, it } from 'vitest';
import { decodeGlyphOutline, glyphControlBox } from '@/features/notation/glyphs/glyphOutline';
import * as metricsModule from '@/features/notation/glyphs/musicGlyphMetrics';
import {
  ENGRAVING_DEFAULTS,
  GLYPH_UNITS_PER_SPACE,
  MUSIC_GLYPH_ANCHORS,
  MUSIC_GLYPH_METRICS,
  MUSIC_GLYPH_NAMES,
} from '@/features/notation/glyphs/musicGlyphMetrics';
import * as outlinesModule from '@/features/notation/glyphs/musicGlyphOutlines';
import { MUSIC_GLYPH_OUTLINES } from '@/features/notation/glyphs/musicGlyphOutlines';

/**
 * The generated glyph modules: complete, consistent with the font's own
 * metadata, and carrying the licence the font is under. Regenerated by
 * `node scripts/extract-music-glyphs.mjs`.
 */

const ROOT = process.cwd();
const GENERATED = [
  'src/features/notation/glyphs/musicGlyphMetrics.ts',
  'src/features/notation/glyphs/musicGlyphOutlines.ts',
];
const LICENCE_FILE = 'public/licenses/music-glyphs-OFL.txt';

/** How far a control box may sit outside the metadata's box, in staff spaces. */
const TOLERANCE_SP = 0.02;

const EXPECTED = [
  'gClef',
  'fClef',
  'gClefChange',
  'fClefChange',
  'brace',
  'noteheadBlack',
  'noteheadHalf',
  'noteheadWhole',
  'augmentationDot',
  'flag8thUp',
  'flag8thDown',
  'flag16thUp',
  'flag16thDown',
  'flag32ndUp',
  'flag32ndDown',
  'flag64thUp',
  'flag64thDown',
  'accidentalFlat',
  'accidentalNatural',
  'accidentalSharp',
  'accidentalDoubleSharp',
  'accidentalDoubleFlat',
  'restWhole',
  'restHalf',
  'restQuarter',
  'rest8th',
  'rest16th',
  'rest32nd',
  'rest64th',
  ...Array.from({ length: 10 }, (_, digit) => `timeSig${digit}`),
  ...Array.from({ length: 10 }, (_, digit) => `tuplet${digit}`),
  'dynamicPiano',
  'dynamicForte',
  'dynamicPPP',
  'dynamicPP',
  'dynamicMP',
  'dynamicMF',
  'dynamicFF',
  'dynamicFFF',
  'ottavaAlta',
  'ottavaBassaVb',
  'metNoteQuarterUp',
];

function read(file: string): string {
  return readFileSync(path.join(ROOT, file), 'utf8');
}

describe('the music glyph modules', () => {
  it('carry every glyph the sheet draws, each with metrics and an outline', () => {
    expect(MUSIC_GLYPH_NAMES).toHaveLength(60);
    expect([...MUSIC_GLYPH_NAMES].sort()).toEqual([...EXPECTED].sort());
    expect(Object.keys(MUSIC_GLYPH_METRICS).sort()).toEqual([...EXPECTED].sort());
    expect(Object.keys(MUSIC_GLYPH_OUTLINES).sort()).toEqual([...EXPECTED].sort());
    for (const name of MUSIC_GLYPH_NAMES) {
      expect(MUSIC_GLYPH_METRICS[name].advance, name).toBeGreaterThan(0);
      expect(MUSIC_GLYPH_OUTLINES[name].length, name).toBeGreaterThan(0);
    }
    expect(GLYPH_UNITS_PER_SPACE).toBe(250);
  });

  it("draws each glyph inside its bounding box, within the tolerance of the font's metadata", () => {
    for (const name of MUSIC_GLYPH_NAMES) {
      const [left, bottom, right, top] = glyphControlBox(
        decodeGlyphOutline(MUSIC_GLYPH_OUTLINES[name]),
      ).map((units) => units / GLYPH_UNITS_PER_SPACE) as [number, number, number, number];
      const box = MUSIC_GLYPH_METRICS[name].bbox;
      // The control box holds the metadata's box…
      expect(left, `${name} left`).toBeLessThanOrEqual(box[0] + 1e-9);
      expect(bottom, `${name} bottom`).toBeLessThanOrEqual(box[1] + 1e-9);
      expect(right, `${name} right`).toBeGreaterThanOrEqual(box[2] - 1e-9);
      expect(top, `${name} top`).toBeGreaterThanOrEqual(box[3] - 1e-9);
      // …and overshoots it by no more than a control point can.
      expect(box[0] - left, `${name} left`).toBeLessThanOrEqual(TOLERANCE_SP);
      expect(box[1] - bottom, `${name} bottom`).toBeLessThanOrEqual(TOLERANCE_SP);
      expect(right - box[2], `${name} right`).toBeLessThanOrEqual(TOLERANCE_SP);
      expect(top - box[3], `${name} top`).toBeLessThanOrEqual(TOLERANCE_SP);
    }
  });

  it('has the proportions the font is known by', () => {
    const [, clefBottom, , clefTop] = MUSIC_GLYPH_METRICS.gClef.bbox;
    expect(clefTop - clefBottom).toBeCloseTo(7.024, 6);
    const [headLeft, headBottom, headRight, headTop] = MUSIC_GLYPH_METRICS.noteheadBlack.bbox;
    expect(headRight - headLeft).toBeCloseTo(1.18, 6);
    expect(headTop - headBottom).toBeCloseTo(1, 6);
    // Time signature digits are two spaces tall, centred on the baseline.
    const [, fourBottom, , fourTop] = MUSIC_GLYPH_METRICS.timeSig4.bbox;
    expect(fourTop - fourBottom).toBeCloseTo(2, 2);
    expect(MUSIC_GLYPH_ANCHORS.noteheadBlack.stemUpSE).toEqual([1.18, 0.168]);
    expect(MUSIC_GLYPH_ANCHORS.noteheadBlack.stemDownNW).toEqual([0, -0.168]);
    expect(MUSIC_GLYPH_ANCHORS.flag32ndUp.stemUpNW).toEqual([0, 0.376]);
    expect(MUSIC_GLYPH_ANCHORS.flag32ndDown.stemDownSW).toEqual([0, -0.448]);
    expect(MUSIC_GLYPH_ANCHORS.dynamicMF.opticalCenter).toEqual([1.796, 0]);
    expect(ENGRAVING_DEFAULTS.stemThickness).toBe(0.12);
    expect(ENGRAVING_DEFAULTS.legerLineThickness).toBe(0.16);
    expect(ENGRAVING_DEFAULTS.legerLineExtension).toBe(0.4);
  });

  it('open with the licence the font is under, and say they are not the font', () => {
    for (const file of GENERATED) {
      const text = read(file);
      expect(text.startsWith('/*! @license\n'), file).toBe(true);
      const legal = text.slice(0, text.indexOf('*/'));
      expect(legal, file).toContain('Steinberg Media Technologies GmbH');
      expect(legal, file).toContain('with Reserved Font Name "Bravura".');
      expect(legal, file).toContain(
        'This subset is a Modified Version of the font and is not named Bravura.',
      );
      expect(legal, file).toContain('SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007');
      expect(legal, file).toContain('TERMINATION');
      expect(text, file).toContain('GENERATED — do not edit.');
      expect(text, file).toContain('node scripts/extract-music-glyphs.mjs');
    }
  });

  it('ship the licence itself where the app serves it, word for word as in the comment', () => {
    const licence = read(LICENCE_FILE);
    expect(licence).toContain('with Reserved Font Name "Bravura".');
    expect(licence).toContain('SIL OPEN FONT LICENSE Version 1.1');
    const comment = read(GENERATED[0]!);
    for (const line of licence.trimEnd().split('\n')) {
      expect(comment).toContain(line === '' ? ' *\n' : ` * ${line}\n`);
    }
  });

  it('name nothing after the font: a Modified Version may not use its name', () => {
    const exported = [...Object.keys(metricsModule), ...Object.keys(outlinesModule)];
    expect(exported.length).toBeGreaterThan(0);
    for (const name of exported) expect(name).not.toMatch(/bravura/i);
    for (const name of MUSIC_GLYPH_NAMES) expect(name).not.toMatch(/bravura/i);
    for (const file of GENERATED) {
      const identifiers = [...read(file).matchAll(/\b(?:const|type|interface)\s+(\w+)/g)].map(
        (match) => match[1]!,
      );
      expect(identifiers.length, file).toBeGreaterThan(0);
      for (const identifier of identifiers) expect(identifier, file).not.toMatch(/bravura/i);
    }
  });
});
